(require 'cljs.repl)
(require 'cljs.build.api)
(require 'cljs.repl.browser)

;; Build the project **before** opening the REPL.
(cljs.build.api/build "src"
                      {:main 'hello-world.core
                       :output-to "out/main.js"
                       :verbose true})

;; Open the REPL. The `:watch` option creates a "watcher" process that automatically recompiles the source code 
;; whenever it changes. Note that the auto building process writes its activity to "out/watch.log". This action
;; allows one to minitor the compilation using `tail -f out/watch.log`. In addition, by specifying the output
;; directory, the REPL resuses the files generated by the build.
(cljs.repl/repl (cljs.repl.browser/repl-env)
                :watch "src"
                :output-dir "out")
