(require 'cljs.build.api)

;; Watch the source directory. When a ClojureScript file changes, this
;; will recompile all the source files to generate out/main.js.
;;
;; The second argument are options to the function. The `:main` option
;; specifies the function to invoke when the generated script is loaded.
;; The `:output-to` option specifies the file generated by the compilation
;; process.
(cljs.build.api/watch "src" {:main 'hello-world.core
                             :output-to "out/main.js"})
